name: Push to GHCR

on:
  push:
    branches: 
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v4
        with:
          strip_tag_prefix: 'v'
      
      - name: Get Short SHA value
        id: short-sha
        run: echo "::set-output name=sha::$(echo ${GITHUB_SHA} | cut -c1 -10)"
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.short-sha.outputs.sha }}
