name: Sync doc assets.

on:
  push:
    branches:
      - main

jobs:
  sync-doc-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Copy CHANGELOG
        uses: docker://pandoc/core:2.13
        with:
          args: -t markdown CHANGELOG.md -t rst --output=docs/source/changelog.rst

      - name: Verify changed files
        id: changed_files
        uses: tj-actions/verify-changed-files@v6.1
        with:
          files: |
            docs/source/changelog.rst

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.9.1
        if: steps.changed_files.outputs.files_changed == 'true'
        with:
          commit-message: Synced README changes to docs
          committer: github-actions[bot] <github-actions[bot]@users.noreply@github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: chore/update-docs
          base: main
          delete-branch: true
          title: Updated docs
          body: |
            Updated docs
            - Auto-generated by github-actions[bot]
          assignees: jackton1
          reviewers: jackton1
