name: Update doc assets.

on:
  push:
    branches:
      - main

jobs:
  sync-doc-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Run remark
        uses: tj-actions/remark@v3

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v10
        id: verify_changed_files
        with:
          files: |
            README.md

      - name: README.md changed
        if: steps.verify_changed_files.outputs.files_changed == 'true'
        run: |
          echo "README.md has uncommited changes"
          exit 1
      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@v4
        with:
          base: "main"
          title: "Updated README.md"
          branch: "chore/update-readme"
          commit-message: "Updated README.md"
          body: "Updated README.md"
          token: ${{ secrets.PAT_TOKEN }}

      - name: Copy CHANGELOG
        uses: docker://pandoc/core:3.13
        with:
          args: -t markdown CHANGELOG.md -t rst --output=docs/source/changelog.rst

      - name: Verify changed files
        id: changed_files
        uses: tj-actions/verify-changed-files@v10
        with:
          files: |
            docs/source/changelog.rst

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.4
        if: steps.changed_files.outputs.files_changed == 'true'
        with:
          commit-message: Synced README changes to docs
          committer: github-actions[bot] <github-actions[bot]@users.noreply@github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: chore/update-docs
          base: main
          delete-branch: true
          title: Updated docs
          body: |
            Updated docs
            - Auto-generated by github-actions[bot]
          assignees: jackton1
          reviewers: jackton1
